### ISSUE TITLE
New Client exeption --weak parameter syntax incorrect

### ISSUE THREAD

**Issue by ghost** [s3inlc/hashtopussy-agent#15]
hello,

just look at your last commit:
{
+                suffixArgs = suffixArgs + "--weak = 0" + suffixExtra;
+            }

is not correct, should be "--weak=0"

--> this is the error when running the client:
hashcat64.exe  --hash-type=2500 "C:\temp\hashlists\2" -a 3 ?d?d?d?d?d?d?d?d --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy --weak = 0
Server requested the client benchmark this task for 30 seconds
The specified parameter cannot use '=' as a value - must be a number.

thanks for changing the code :-D i dont have my linux box here just now otherwith i would change that

**Comment by blazer2x** [comment]
Hi, good pickup
Fixed  https://github.com/s3inlc/hashtopussy-agent/commit/bf97b279793c63ee1e42a73c1b5fac629c9d5e61

**Comment by s3inlc** [comment]
This issue should be fixed and can therefore safely be closed.
