### ISSUE TITLE
Passing API Url via Command Line

### ISSUE THREAD

**Issue by nikeee** [s3inlc/hashtopussy-agent#21]
Is it possible to pass the API url/Token via the command line? This would simplify some deployment scenarios for me.
(C# agent)

**Comment by winxp5421** [comment]
Unfortunately no you cannot call hashtopussy.exe with arguments like url and token ( that I'm aware of ) but you could simply create those files the executable looks for before running the hashtopussy binary that would look something like this. 'echo "<API URL>" > URL && echo "<token>" > TOKEN && hashtopussy.exe'  as long as the file name "URL" is in the same directory as hashtopussy.exe your good. Side note voucher and token are not the same.

**Comment by nikeee** [comment]
Is there any plan to implement this (possibly via PR)?

**Comment by winxp5421** [comment]
Currently I don't know a "plan" to implement this right at this point in time. I do see the benefits and would love to have this a feature and plan to keep this issue open until this is implemented by our C# dev. However, with that being said we by no means will discourage anyone from submitting a PR ;) and welcome it.

**Comment by s3inlc** [comment]
With the upcoming version it would be possible to make this on the python client without any change on the communication API. As deletion of used vouchers can be disabled, you could ship the python zip containing this voucher and the url inside and the client checks then if this is present and registers himself without any input.
Was this something similar you thought about? @nikeee

**Comment by nikeee** [comment]
This seems okay.
I'm also currently thinking about forking the C# agent.

**Comment by blazer2x** [comment]
Hi
These features have just been added to the dev branch 
https://github.com/s3inlc/hashtopussy-agent/commit/ff349d6909233360115aed2264a448ba32e4a298
https://github.com/s3inlc/hashtopussy-agent/commit/aee591e8c4be0bf0601edd971fcea57689ba7882

Using /u and /t options eg
/u:URL
/t:[TOKEN]

Also the debug switch has been changed to /d

These are preliminary changes and some additional checks will be added.
