### ISSUE TITLE
Catch error on keyspace

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopussy-agent#6]
In the case the keyspace is 0, which would definitely mean that there is something not correct (either there was an error in hashcat or the task was configured wrong, e.g. the length for a wpa was smaller than 8 chars), the client should print or send an error instead of just sending 0 as keyspace result, which will result in a loop because the server will always issue 'keyspace_required' as long as it is 0.

**Comment by blazer2x** [comment]
Fixed here

https://github.com/s3inlc/hashtopussy-agent/commit/8b3ec088db2196b0f095377502ce828544189b3f
