### ISSUE TITLE
WPA download problem

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopussy-agent#7]
When the client downloads a wpa hash (I think it also will apply to other binary hashes), the server will then send just the binary data. 
Somewhere in retrieving and saving the data to a file it gets messed up. In case of the WPA, the file always should be 393 Bytes, but with the current client the file has size 385B.

I tested that the server definitely sends out the data correctly, it can be piped into a file and it matches the original hccapx exactly. I suspect that the data "corruption" happens when the binary data is treated as string and it might try to decode it as a readable string before it gets written.

**Comment by blazer2x** [comment]
Fixed https://github.com/s3inlc/hashtopussy-agent/commit/1be32b746bd5a3b68dc28d0c4e2f86e8c8bfac31
